### ISSUE TITLE
cert file

### ISSUE THREAD

**Issue by chavers** [ezBastion/ezb_vault#1]
Add the certificat creation in the setup process.

**Comment by jfbutkiewicz** [comment]
New environment (GITHUB based) done, cross compiling OK, I'm starting the job.

**Comment by chavers** [comment]
Good news.

**Comment by jfbutkiewicz** [comment]
Cert folder can be added but set to cert by default. No cert name stores in the conf file

**Comment by chavers** [comment]
close by #3
